### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/About-Us#3]
create a "recent highlights" page that includes links to news articles, agency brochures, AGU/EGU abstracts, etc

**Comment by duvivier** [comment]
@eclare108213 @apcraig 
After brief discussion with @eclare108213 I made this page:
https://github.com/CICE-Consortium/About-Us/wiki/Consortium-News-and-Highlights

At the bottom it links to past news so that we can keep a record but without the images:
https://github.com/CICE-Consortium/About-Us/wiki/Past-Consortium-News-and-Highlights

Let me know what you think should change. I ended up putting more text than I'd anticipated but I don't think it's unreasonable. 

I think we should probably go ahead and directly link this wiki page under each repo's README.md as one of the useful links. I don't want to bury it in the Resource Index since the point of this page is that we want people to look at it quickly. However, I want your feedback before I make the README.md changes prior to the release.
